-- This file is UTF-8 (it contains an emoji default). Make psql read it as UTF-8 whatever the console code page is.
SET client_encoding = 'UTF8';

-- ============================================================================
-- VEDIQRA backend — PostgreSQL schema (originally reconstructed from the GFTD codebase; see FIXES_README.md)
-- Generated by inspecting backend/src/routes/**, backend/src/utils/db.ts and
-- backend/src/middleware/auth.ts. No old data is restored — this creates an
-- EMPTY database with the structure the current backend code requires.
--
-- Safe to run once against a brand new, empty PostgreSQL database:
--   psql "$DATABASE_URL" -f database/schema.sql
-- ============================================================================

-- ---------------------------------------------------------------------------
-- EXTENSIONS
-- ---------------------------------------------------------------------------
-- gen_random_uuid() (used for every primary key below) lives in pgcrypto on
-- PostgreSQL < 13. On PG >= 13 it is also available from core, but creating
-- pgcrypto is harmless and keeps this script portable.
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- ---------------------------------------------------------------------------
-- SLUG HELPERS (Phase 2)
-- ---------------------------------------------------------------------------
-- "Magic Mug" -> "magic-mug". Non-latin names fall back to "item" (made unique by unique_slug).
CREATE OR REPLACE FUNCTION slugify(input text) RETURNS text
LANGUAGE sql IMMUTABLE AS $$
  SELECT COALESCE(
    NULLIF(trim(both '-' from regexp_replace(lower(coalesce(input, '')), '[^a-z0-9]+', '-', 'g')), ''),
    'item')
$$;

-- First free slug in <tbl>.slug for a base: base, base-2, base-3 ...
CREATE OR REPLACE FUNCTION unique_slug(tbl text, base text) RETURNS text
LANGUAGE plpgsql AS $$
DECLARE
  candidate text := base;
  n integer := 1;
  taken boolean;
BEGIN
  LOOP
    EXECUTE format('SELECT EXISTS (SELECT 1 FROM %I WHERE slug = $1)', tbl) INTO taken USING candidate;
    EXIT WHEN NOT taken;
    n := n + 1;
    candidate := base || '-' || n;
  END LOOP;
  RETURN candidate;
END $$;

-- BEFORE INSERT: derive slug from name when the caller did not supply one.
CREATE OR REPLACE FUNCTION assign_slug_from_name() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
  IF NEW.slug IS NULL OR NEW.slug = '' THEN
    NEW.slug := unique_slug(TG_TABLE_NAME, slugify(NEW.name));
  END IF;
  RETURN NEW;
END $$;


-- ============================================================================
-- GENDERS  (backend/src/routes/genders.ts)
-- ============================================================================
CREATE TABLE genders (
    id             UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name           TEXT NOT NULL UNIQUE,
    display_name   TEXT NOT NULL,
    icon           TEXT,
    display_order  INTEGER NOT NULL DEFAULT 0,
    is_active      BOOLEAN NOT NULL DEFAULT TRUE,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ============================================================================
-- CATEGORIES  (backend/src/routes/categories.ts, admin.ts)
-- ============================================================================
CREATE TABLE categories (
    id             UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name           TEXT NOT NULL,
    description    TEXT,
    icon           TEXT DEFAULT 'Gift',
    icon_type      TEXT NOT NULL DEFAULT 'lucide',   -- 'lucide' | 'emoji' | 'image'
    image_url      TEXT,
    color          TEXT DEFAULT 'from-pink-100 to-pink-50',
    hover_effect   TEXT DEFAULT 'scale',
    display_order  INTEGER NOT NULL DEFAULT 0,
    gender         TEXT,                              -- optional gender scoping, set by admin.ts POST /admin/categories
    is_active      BOOLEAN NOT NULL DEFAULT TRUE,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    -- Phase 2: URL slug (auto-filled from name when omitted), optional parent (two levels), banner image
    slug           TEXT NOT NULL CONSTRAINT categories_slug_key UNIQUE
                        CONSTRAINT categories_slug_format CHECK (slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$'),
    parent_id      UUID CONSTRAINT categories_parent_fk REFERENCES categories(id) ON DELETE RESTRICT
                        CONSTRAINT categories_not_own_parent CHECK (parent_id IS NULL OR parent_id <> id),
    banner_url     TEXT
);

CREATE INDEX idx_categories_display_order ON categories (display_order);
CREATE INDEX idx_categories_is_active ON categories (is_active);
CREATE INDEX idx_categories_parent ON categories (parent_id);

-- Two levels only: a parent must itself be top-level, and a category that has children cannot become a child.
-- (Remove this trigger if deeper nesting is ever wanted; nothing else depends on it.)
CREATE OR REPLACE FUNCTION categories_check_hierarchy() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
  IF NEW.parent_id IS NOT NULL THEN
    IF EXISTS (SELECT 1 FROM categories WHERE id = NEW.parent_id AND parent_id IS NOT NULL) THEN
      RAISE EXCEPTION 'Categories support two levels: the parent must be a top-level category';
    END IF;
    IF TG_OP = 'UPDATE' AND EXISTS (SELECT 1 FROM categories WHERE parent_id = NEW.id) THEN
      RAISE EXCEPTION 'A category that has subcategories cannot become a subcategory';
    END IF;
  END IF;
  RETURN NEW;
END $$;

DROP TRIGGER IF EXISTS trg_categories_hierarchy ON categories;
CREATE TRIGGER trg_categories_hierarchy
  BEFORE INSERT OR UPDATE OF parent_id ON categories
  FOR EACH ROW EXECUTE FUNCTION categories_check_hierarchy();

DROP TRIGGER IF EXISTS trg_categories_slug ON categories;
CREATE TRIGGER trg_categories_slug
  BEFORE INSERT ON categories
  FOR EACH ROW EXECUTE FUNCTION assign_slug_from_name();


-- ============================================================================
-- PRODUCTS  (backend/src/routes/products.ts, admin.ts, social-proof.ts)
-- ============================================================================
CREATE TABLE products (
    id                              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name                            TEXT NOT NULL,
    description                     TEXT,
    price                           NUMERIC(12,2) NOT NULL,
    original_price                  NUMERIC(12,2),
    discount_percentage             NUMERIC(5,2),
    image_url                       TEXT,
    additional_images               TEXT[] DEFAULT '{}',
    stock_quantity                  INTEGER NOT NULL DEFAULT 0,
    track_stock                     BOOLEAN NOT NULL DEFAULT FALSE,   -- TRUE: stock_quantity is enforced/decremented; FALSE: made to order
    sku                             TEXT,
    gender                          TEXT DEFAULT 'unisex',
    category                        TEXT,             -- legacy free-text category label (kept alongside product_categories)
    is_customizable                 BOOLEAN NOT NULL DEFAULT FALSE,
    customization_price             NUMERIC(12,2) DEFAULT 0,
    max_customization_characters    INTEGER DEFAULT 50,
    max_customization_images        INTEGER DEFAULT 10,
    max_customization_lines         INTEGER DEFAULT 0,
    is_active                       BOOLEAN NOT NULL DEFAULT TRUE,
    has_colors                      BOOLEAN NOT NULL DEFAULT FALSE,
    has_sizes                       BOOLEAN NOT NULL DEFAULT FALSE,
    social_proof_enabled            BOOLEAN NOT NULL DEFAULT TRUE,
    social_proof_text               TEXT DEFAULT '🔺 {count} people are viewing this right now',
    social_proof_initial_count      INTEGER DEFAULT 5,
    social_proof_end_count          INTEGER DEFAULT 15,
    created_at                      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at                      TIMESTAMPTZ NOT NULL DEFAULT now(),
    -- Phase 2: unique URL slug (auto-filled from name when omitted)
    slug                            TEXT NOT NULL CONSTRAINT products_slug_key UNIQUE
                                         CONSTRAINT products_slug_format CHECK (slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$')
);

DROP TRIGGER IF EXISTS trg_products_slug ON products;
CREATE TRIGGER trg_products_slug
  BEFORE INSERT ON products
  FOR EACH ROW EXECUTE FUNCTION assign_slug_from_name();

CREATE INDEX idx_products_is_active ON products (is_active);
CREATE INDEX idx_products_gender ON products (LOWER(gender));
CREATE INDEX idx_products_created_at ON products (created_at DESC);
CREATE INDEX idx_products_name_trgm ON products (name);

-- ============================================================================
-- PRODUCT <-> CATEGORY  (many-to-many)
-- ============================================================================
CREATE TABLE product_categories (
    id           UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    product_id   UUID NOT NULL REFERENCES products(id) ON DELETE CASCADE,
    category_id  UUID NOT NULL REFERENCES categories(id) ON DELETE CASCADE,
    UNIQUE (product_id, category_id)   -- required: routes use ON CONFLICT DO NOTHING
);

CREATE INDEX idx_product_categories_product ON product_categories (product_id);
CREATE INDEX idx_product_categories_category ON product_categories (category_id);

-- ============================================================================
-- PRODUCT COLOR VARIANTS  (product-colors.ts, product-colors-public.ts)
-- ============================================================================
CREATE TABLE product_colors (
    id                 UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    product_id         UUID NOT NULL REFERENCES products(id) ON DELETE CASCADE,
    color_name         TEXT NOT NULL,
    color_code         TEXT,
    image_url          TEXT,
    additional_images  TEXT[] DEFAULT '{}',
    stock_quantity     INTEGER NOT NULL DEFAULT 0,
    price_modifier     NUMERIC(12,2) NOT NULL DEFAULT 0,
    is_active          BOOLEAN NOT NULL DEFAULT TRUE,
    display_order      INTEGER NOT NULL DEFAULT 0,
    created_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at         TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_product_colors_product ON product_colors (product_id);

-- ============================================================================
-- PRODUCT SIZE VARIANTS  (product-sizes.ts)
-- ============================================================================
CREATE TABLE product_sizes (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    product_id      UUID NOT NULL REFERENCES products(id) ON DELETE CASCADE,
    size_name       TEXT NOT NULL,
    size_code       TEXT,
    stock_quantity  INTEGER NOT NULL DEFAULT 0,
    price_modifier  NUMERIC(12,2) NOT NULL DEFAULT 0,
    is_active       BOOLEAN NOT NULL DEFAULT TRUE,
    display_order   INTEGER NOT NULL DEFAULT 0,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_product_sizes_product ON product_sizes (product_id);

-- ---------------------------------------------------------------------------
-- 4. Generic product options
--
--   Product --(product_option_groups)--> Option group --> Values (per product)
--
-- Nothing is global: a value exists only under one product's attachment of a group, so "Size: M" on a
-- T-shirt and "Size: M" on a mug are independent rows with their own price and stock.
-- The database has no idea what "Finish" or "Size" mean; the storefront decides how to render a group.
-- ---------------------------------------------------------------------------
CREATE TABLE option_groups (
    id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name        TEXT NOT NULL,
    slug        TEXT NOT NULL UNIQUE CHECK (slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$'),
    is_active   BOOLEAN NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- One library group per name ("Finish" cannot exist twice, whatever its slug).
CREATE UNIQUE INDEX uq_option_groups_name ON option_groups (lower(name));

DROP TRIGGER IF EXISTS trg_option_groups_slug ON option_groups;
CREATE TRIGGER trg_option_groups_slug
  BEFORE INSERT ON option_groups
  FOR EACH ROW EXECUTE FUNCTION assign_slug_from_name();

CREATE TABLE product_option_groups (
    id               UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    product_id       UUID NOT NULL REFERENCES products(id) ON DELETE CASCADE,
    option_group_id  UUID NOT NULL REFERENCES option_groups(id) ON DELETE RESTRICT,
    is_required      BOOLEAN NOT NULL DEFAULT FALSE,
    display_order    INTEGER NOT NULL DEFAULT 0,
    is_active        BOOLEAN NOT NULL DEFAULT TRUE,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (product_id, option_group_id)
);
CREATE INDEX idx_pog_product ON product_option_groups (product_id);
CREATE INDEX idx_pog_group ON product_option_groups (option_group_id);

-- Unique-within-group key for a value ("Holographic" -> "holographic"; a repeat becomes "holographic-2").
CREATE OR REPLACE FUNCTION assign_option_value_key() RETURNS trigger
LANGUAGE plpgsql AS $$
DECLARE
  base text;
  candidate text;
  n integer := 1;
BEGIN
  IF NEW.value_key IS NULL OR NEW.value_key = '' THEN
    base := slugify(NEW.name);
    candidate := base;
    WHILE EXISTS (SELECT 1 FROM product_option_values
                   WHERE product_option_group_id = NEW.product_option_group_id AND value_key = candidate) LOOP
      n := n + 1;
      candidate := base || '-' || n;
    END LOOP;
    NEW.value_key := candidate;
  END IF;
  RETURN NEW;
END $$;

CREATE TABLE product_option_values (
    id                       UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    product_option_group_id  UUID NOT NULL REFERENCES product_option_groups(id) ON DELETE CASCADE,
    name                     TEXT NOT NULL,
    value_key                TEXT NOT NULL CHECK (value_key ~ '^[a-z0-9]+(-[a-z0-9]+)*$'),
    price_modifier           NUMERIC(12,2) NOT NULL DEFAULT 0,   -- added to the product price (may be negative)
    stock_quantity           INTEGER CHECK (stock_quantity IS NULL OR stock_quantity >= 0), -- NULL = not tracked
    display_order            INTEGER NOT NULL DEFAULT 0,
    is_active                BOOLEAN NOT NULL DEFAULT TRUE,
    image_url                TEXT,
    metadata                 JSONB NOT NULL DEFAULT '{}'::jsonb, -- storefront hints, e.g. {"color_code":"#f00","size_code":"XL"}
    created_at               TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at               TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (product_option_group_id, value_key)
);
CREATE INDEX idx_pov_group ON product_option_values (product_option_group_id);
-- Lets cart items created before this migration (they carry old colour/size ids) be mapped to option values.
CREATE INDEX idx_pov_legacy_color ON product_option_values ((metadata->>'legacy_color_id')) WHERE metadata ? 'legacy_color_id';
CREATE INDEX idx_pov_legacy_size  ON product_option_values ((metadata->>'legacy_size_id'))  WHERE metadata ? 'legacy_size_id';

DROP TRIGGER IF EXISTS trg_pov_value_key ON product_option_values;
CREATE TRIGGER trg_pov_value_key
  BEFORE INSERT ON product_option_values
  FOR EACH ROW EXECUTE FUNCTION assign_option_value_key();

-- Library groups that the legacy colour/size adapters (and the storefront) expect to exist.
INSERT INTO option_groups (name, slug) VALUES ('Colour', 'colour'), ('Size', 'size');


-- ============================================================================
-- COMBOS  (combos.ts, admin.ts)
-- ============================================================================
CREATE TABLE combos (
    id                    UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name                  TEXT NOT NULL,
    description           TEXT,
    discount_percentage   NUMERIC(5,2),
    discount_price        NUMERIC(12,2),
    image_url             TEXT,
    additional_images     TEXT[] DEFAULT '{}',
    is_active             BOOLEAN NOT NULL DEFAULT TRUE,
    created_at            TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at            TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_combos_is_active ON combos (is_active);
CREATE INDEX idx_combos_created_at ON combos (created_at DESC);

-- ============================================================================
-- COMBO <-> PRODUCT  (many-to-many with quantity)
-- ============================================================================
CREATE TABLE combo_products (
    id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    combo_id    UUID NOT NULL REFERENCES combos(id) ON DELETE CASCADE,
    product_id  UUID NOT NULL REFERENCES products(id) ON DELETE RESTRICT,
    quantity    INTEGER NOT NULL DEFAULT 1 CHECK (quantity > 0),
    UNIQUE (combo_id, product_id)   -- required: bulk endpoint uses ON CONFLICT (combo_id, product_id)
);

CREATE INDEX idx_combo_products_combo ON combo_products (combo_id);
CREATE INDEX idx_combo_products_product ON combo_products (product_id);

-- ============================================================================
-- COMBO <-> CATEGORY  (many-to-many, used for combo filtering)
-- ============================================================================
CREATE TABLE combo_categories (
    id           UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    combo_id     UUID NOT NULL REFERENCES combos(id) ON DELETE CASCADE,
    category_id  UUID NOT NULL REFERENCES categories(id) ON DELETE CASCADE
);

CREATE INDEX idx_combo_categories_combo ON combo_categories (combo_id);
CREATE INDEX idx_combo_categories_category ON combo_categories (category_id);

-- ============================================================================
-- CUSTOM (BUILD-YOUR-OWN) COMBOS  (combos.ts POST /custom)
-- ============================================================================
CREATE TABLE custom_combos (
    id                    UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name                  TEXT NOT NULL DEFAULT 'Custom Combo',
    description           TEXT,
    subtotal              NUMERIC(12,2),
    discount_percentage   NUMERIC(5,2),
    discount_amount       NUMERIC(12,2),
    total_price           NUMERIC(12,2),
    item_count            INTEGER,
    special_requests      TEXT,
    status                TEXT NOT NULL DEFAULT 'pending',
    created_at            TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE custom_combo_products (
    id                UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    custom_combo_id   UUID NOT NULL REFERENCES custom_combos(id) ON DELETE CASCADE,
    product_id        UUID NOT NULL REFERENCES products(id) ON DELETE RESTRICT,
    quantity          INTEGER NOT NULL DEFAULT 1 CHECK (quantity > 0)
);

CREATE INDEX idx_custom_combo_products_combo ON custom_combo_products (custom_combo_id);

-- ============================================================================
-- ORDERS  (orders.ts, payment.ts, admin.ts)
-- Line items are stored denormalized as JSONB in `items` — the backend never
-- writes normalized rows for an order's line items (see order_items below).
-- ============================================================================
CREATE TABLE orders (
    id                     UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    custom_order_id        TEXT UNIQUE,             -- e.g. "VEDIQRA#101" (prefix is configurable via ORDER_ID_PREFIX, see backend/src/config.ts)
    razorpay_order_id      TEXT,
    razorpay_payment_id    TEXT,
    razorpay_signature     TEXT,
    items                  JSONB NOT NULL DEFAULT '[]'::jsonb,
    subtotal               NUMERIC(12,2) DEFAULT 0,
    shipping_charge        NUMERIC(12,2) DEFAULT 0,
    cod_charge             NUMERIC(12,2),
    coupon_code            TEXT,
    coupon_discount        NUMERIC(12,2) DEFAULT 0,
    total_amount           NUMERIC(12,2) NOT NULL DEFAULT 0,
    grand_total            NUMERIC(12,2),
    customer_name          TEXT NOT NULL,
    customer_email         TEXT NOT NULL,
    customer_phone         TEXT NOT NULL,
    special_requests       TEXT,
    shipping_address       TEXT,
    shipping_city          TEXT,
    shipping_state         TEXT,
    shipping_pincode       TEXT,
    shipping_country       TEXT DEFAULT 'India',
    payment_method         TEXT NOT NULL DEFAULT 'cod',   -- 'cod' | 'online'
    status                 TEXT NOT NULL DEFAULT 'pending',
    tracking_number        TEXT,                          -- set by admin when shipping
    admin_notes            TEXT,
    paid_at                TIMESTAMPTZ,
    refund_data            JSONB,
    refunded_at            TIMESTAMPTZ,
    -- Phase 3B: stock ledger and refund tracking (see migrations/004_stock_restoration_and_refunds.sql)
    stock_movements        JSONB NOT NULL DEFAULT '[]'::jsonb,   -- stock actually decremented for this order
    stock_restored_at      TIMESTAMPTZ,                          -- set once when that stock was given back
    refunded_amount        NUMERIC(12,2) NOT NULL DEFAULT 0,     -- provider-confirmed refunds, rupees
    refunds                JSONB NOT NULL DEFAULT '[]'::jsonb,   -- [{id, request_id, amount, status, created_at}]
    created_at             TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at             TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT orders_refund_bounds CHECK (refunded_amount >= 0 AND refunded_amount <= total_amount)
);

CREATE INDEX idx_orders_created_at ON orders (created_at DESC);
CREATE INDEX idx_orders_status ON orders (status);
CREATE INDEX idx_orders_customer_phone ON orders (customer_phone);
CREATE INDEX idx_orders_customer_email ON orders (customer_email);
CREATE INDEX idx_orders_razorpay_order_id ON orders (razorpay_order_id);
-- One order per Razorpay payment: makes payment verification idempotent (retries cannot duplicate an order)
CREATE UNIQUE INDEX uq_orders_razorpay_payment_id ON orders (razorpay_payment_id) WHERE razorpay_payment_id IS NOT NULL;

-- Atomic order numbers (custom_order_id = <prefix>#<n>). Replaces "read the last order and add 1", which
-- produced duplicate numbers under concurrent checkouts.
CREATE SEQUENCE order_number_seq START WITH 100 MINVALUE 100;

-- ============================================================================
-- ORDER_ITEMS
-- NOTE: No route in this backend ever INSERTs into this table — order line
-- items live entirely inside orders.items (JSONB). The only reference is a
-- pre-delete safety check in admin.ts ("has this product ever been ordered?").
-- Table is created so that query does not fail against an empty database;
-- see the report for the recommendation to either wire this up or remove the
-- check. Shape below is inferred from the fields used in orders.items entries
-- (see backend/src/utils/emailTemplates.ts).
-- ============================================================================
CREATE TABLE order_items (
    id                    UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    order_id              UUID NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
    product_id            UUID REFERENCES products(id) ON DELETE SET NULL,
    combo_id              UUID REFERENCES combos(id) ON DELETE SET NULL,
    name                  TEXT,
    quantity              INTEGER NOT NULL DEFAULT 1,
    price                 NUMERIC(12,2) NOT NULL DEFAULT 0,
    color_id              UUID REFERENCES product_colors(id) ON DELETE SET NULL,
    color_name            TEXT,
    size_id               UUID REFERENCES product_sizes(id) ON DELETE SET NULL,
    size_name             TEXT,
    size_code             TEXT,
    customization_data    JSONB,
    created_at            TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_order_items_order ON order_items (order_id);
CREATE INDEX idx_order_items_product ON order_items (product_id);

-- ============================================================================
-- COUPONS  (coupons.ts)
-- ============================================================================
CREATE TABLE coupons (
    id                      UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    code                    TEXT NOT NULL UNIQUE,
    description             TEXT,
    discount_type           TEXT NOT NULL CHECK (discount_type IN ('percentage', 'fixed')),
    discount_value          NUMERIC(12,2) NOT NULL,
    min_order_amount        NUMERIC(12,2),
    max_discount_amount     NUMERIC(12,2),
    usage_limit             INTEGER DEFAULT 100,
    used_count              INTEGER NOT NULL DEFAULT 0,
    per_user_limit          INTEGER DEFAULT 1,
    start_date              TIMESTAMPTZ,
    end_date                TIMESTAMPTZ,
    applicable_categories   TEXT[] DEFAULT '{}',
    is_active               BOOLEAN NOT NULL DEFAULT TRUE,
    created_at              TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at              TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_coupons_is_active ON coupons (is_active);

-- ============================================================================
-- COUPON USAGE  (coupons.ts, orders.ts, payment.ts)
-- ============================================================================
CREATE TABLE coupon_usage (
    id                UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    coupon_id         UUID NOT NULL REFERENCES coupons(id) ON DELETE CASCADE,
    order_id          UUID REFERENCES orders(id) ON DELETE CASCADE,
    customer_email    TEXT,
    discount_amount   NUMERIC(12,2),
    used_at           TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_coupon_usage_coupon ON coupon_usage (coupon_id);
CREATE INDEX idx_coupon_usage_email ON coupon_usage (coupon_id, customer_email);

-- ============================================================================
-- REVIEWS  (reviews.ts)
-- ============================================================================
CREATE TABLE reviews (
    id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    product_id    UUID NOT NULL REFERENCES products(id) ON DELETE CASCADE,
    user_name     TEXT NOT NULL,
    user_email    TEXT,
    rating        INTEGER NOT NULL CHECK (rating BETWEEN 1 AND 5),
    comment       TEXT NOT NULL,
    is_approved   BOOLEAN NOT NULL DEFAULT FALSE,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_reviews_product ON reviews (product_id);
CREATE INDEX idx_reviews_is_approved ON reviews (is_approved);

-- ============================================================================
-- SOCIAL PROOF STATS  (social-proof.ts)
-- ============================================================================
CREATE TABLE social_proof_stats (
    id               UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    product_id       UUID NOT NULL REFERENCES products(id) ON DELETE CASCADE,
    view_count       INTEGER NOT NULL DEFAULT 0,
    purchase_count   INTEGER NOT NULL DEFAULT 0,
    last_updated     TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (product_id)   -- required: routes use ON CONFLICT (product_id) DO UPDATE
);

-- ============================================================================
-- HERO CONTENT  (hero.ts, adminHero.ts)
-- ============================================================================
CREATE TABLE hero_content (
    id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    title               TEXT NOT NULL,
    subtitle            TEXT,
    media_type          TEXT NOT NULL DEFAULT 'image',   -- 'image' | 'video'
    media_url           TEXT NOT NULL,
    video_poster_url    TEXT,
    autoplay            BOOLEAN NOT NULL DEFAULT TRUE,
    loop                BOOLEAN NOT NULL DEFAULT TRUE,
    muted               BOOLEAN NOT NULL DEFAULT TRUE,
    cta_text            TEXT,
    cta_link            TEXT,
    content_alignment   TEXT NOT NULL DEFAULT 'center',  -- 'left' | 'center' | 'right'
    is_active           BOOLEAN NOT NULL DEFAULT TRUE,
    display_order       INTEGER NOT NULL DEFAULT 0,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_hero_content_display_order ON hero_content (display_order);

-- ============================================================================
-- LOGO CONFIG  (logo.ts)
-- ============================================================================
CREATE TABLE logo_config (
    id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    logo_url      TEXT NOT NULL,
    favicon_url   TEXT,
    start_date    TIMESTAMPTZ,
    end_date      TIMESTAMPTZ,
    is_active     BOOLEAN NOT NULL DEFAULT TRUE,
    notes         TEXT,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ============================================================================
-- POPUP CONFIG + DISPLAY STATS  (popups.ts, adminPopups.ts)
-- ============================================================================
CREATE TABLE popup_config (
    id                        UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    title                     TEXT NOT NULL,
    description               TEXT,
    image_url                 TEXT,
    discount_text             TEXT,
    discount_value            TEXT,
    timer_enabled             BOOLEAN NOT NULL DEFAULT TRUE,
    timer_hours               INTEGER NOT NULL DEFAULT 0,
    timer_minutes             INTEGER NOT NULL DEFAULT 59,
    timer_seconds             INTEGER NOT NULL DEFAULT 46,
    offer_text                TEXT,
    cta_text                  TEXT,
    cta_link                  TEXT,
    cash_on_delivery_text     TEXT,
    prepaid_discount_text     TEXT,
    is_active                 BOOLEAN NOT NULL DEFAULT TRUE,
    display_frequency         TEXT NOT NULL DEFAULT 'once_per_session', -- 'once_per_session' | 'always' | 'once_per_day'
    start_date                TIMESTAMPTZ,
    end_date                  TIMESTAMPTZ,
    created_at                TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at                TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE popup_display_stats (
    id           UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    popup_id     UUID NOT NULL REFERENCES popup_config(id) ON DELETE CASCADE,
    session_id   TEXT,
    viewed_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    clicked_at   TIMESTAMPTZ
);

CREATE INDEX idx_popup_display_stats_popup ON popup_display_stats (popup_id);

-- ============================================================================
-- SITE SETTINGS  (settings.ts) — simple generic key/value store
-- ============================================================================
CREATE TABLE site_settings (
    key          TEXT PRIMARY KEY,
    value        JSONB,
    updated_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ============================================================================
-- ADMIN USERS  (routes/adminAuth.ts, middleware/auth.ts)
-- Passwords are stored ONLY as bcrypt hashes. Create the first admin with:
--   cd backend && npm run create-admin -- <username> <password>
-- ============================================================================
CREATE TABLE admin_users (
    id             UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    username       TEXT NOT NULL UNIQUE CHECK (username = lower(username)),
    password_hash  TEXT NOT NULL,
    role           TEXT NOT NULL DEFAULT 'admin',
    is_active      BOOLEAN NOT NULL DEFAULT TRUE,
    last_login_at  TIMESTAMPTZ,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);

COMMENT ON COLUMN products.track_stock IS 'TRUE: stock_quantity is enforced and decremented on order. FALSE: made to order, not tracked.';
COMMENT ON COLUMN product_option_values.stock_quantity IS 'NULL = not tracked (unlimited). A number is enforced and decremented on order.';
COMMENT ON COLUMN orders.stock_movements   IS 'Stock actually decremented for this order (products with track_stock, option values with tracked stock). Source of truth for restoration.';
COMMENT ON COLUMN orders.stock_restored_at IS 'Set once when stock_movements were given back (cancellation / full refund). Prevents double restoration.';
COMMENT ON COLUMN orders.refunded_amount   IS 'Total of provider-confirmed refunds, in rupees.';
COMMENT ON COLUMN orders.refunds           IS 'Provider-confirmed refunds: [{id, request_id, amount, status, created_at}].';
COMMENT ON TABLE product_colors IS 'DEPRECATED (Phase 2): migrated to product_option_values under group "colour". Not read by the API any more; drop after the old admin UI is retired.';
COMMENT ON TABLE product_sizes  IS 'DEPRECATED (Phase 2): migrated to product_option_values under group "size". Not read by the API any more; drop after the old admin UI is retired.';
COMMENT ON TABLE order_items    IS 'UNUSED: order lines are stored as an immutable JSONB snapshot in orders.items (product, base price, selected options with their prices, customization, quantity, line price).';


-- ============================================================================
-- End of schema
-- ============================================================================
